name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --project=tests
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-blob-report
          path: blob-report
          retention-days: 1

      - name: Run Playwright tests-examples
        run: npx playwright test --project=tests-examples
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ex-blob-reports
          path: blob-report
          retention-days: 1
  create-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install

      - name: Download test blob reports
        uses: actions/download-artifact@v4
        with:
          name: test-blob-report
          path: all-blob-reports/test

      - name: Download example blob reports
        uses: actions/download-artifact@v4
        with:
          name: ex-blob-reports
          path: all-blob-reports/examples

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 7
